config-user: pre-commit hook now prompts user once for all files, instead of once per file

diff --git a/charts/config-user/files/pre-commit b/charts/config-user/files/pre-commit
--- a/charts/config-user/files/pre-commit
+++ b/charts/config-user/files/pre-commit
@@ -8,25 +8,30 @@ exec 1>&2
 FILE_SIZE_LIMIT=5  # In MB
 HAS_ERROR=""
 
-exec < /dev/tty
-
 for file in $(git diff --cached --name-only | sort | uniq); do
     file_size=$(du --apparent-size -m $(pwd)/$file | awk '{print $1}')
     if [ "$file_size" -ge $FILE_SIZE_LIMIT ]; then
-        while true; do
-            read -p "${file} is larger than ${FILE_SIZE_LIMIT}MB. Do you wish to commit anyway? (Y/n) " yn
-            if [ "$yn" = "" ]; then
-                yn='N'
-            fi
-            case $yn in
-              [Yy] )
-                break;;
-              [Nn] )
-                echo -e "Commit aborted. Please unstage oversize file with:\n\n\tgit reset ${file}\n";
-                exit 1;;
-              * )
-                echo -e "Please answer y or n for yes or no.";;
-            esac
-        done
+        echo "$file is larger than the ${FILE_SIZE_LIMIT}MB limit."
+        HAS_ERROR="1"
     fi
 done
+
+if [ "$HAS_ERROR" != "" ]; then
+    exec < /dev/tty
+
+    while true; do
+        read -p "Do you wish to commit anyway? (Y/n) " yn
+        if [ "$yn" = "" ]; then
+            yn='N'
+        fi
+        case $yn in
+          [Yy] )
+            exit 0;;
+          [Nn] )
+            echo -e "\nCommit aborted. Please unstage oversize files with:\n\n\tgit reset FILENAME\n";
+            exit 1;;
+          * )
+            echo -e "\nPlease answer y or n for yes or no.";;
+        esac
+    done
+fi
